// Generated by CoffeeScript 1.6.2
var GalleryAddController, GalleryEditController, GalleryListController, ImageAddController, ImageListController, SweetGalleryApp;

SweetGalleryApp = angular.module('SweetGalleryApp', ['ngResource', '$strap.directives', 'ngUpload']);

SweetGalleryApp.config(function($routeProvider) {
  return $routeProvider.when('/', {
    controller: 'GalleryListController',
    templateUrl: 'app/view/galleryList.html'
  }).when('/gallery/add', {
    controller: 'GalleryAddController',
    templateUrl: 'app/view/galleryAdd.html'
  }).when('/gallery/edit/:_id', {
    controller: 'GalleryEditController',
    templateUrl: 'app/view/galleryAdd.html'
  }).when('/gallery/:galleryId/images', {
    controller: 'ImageListController',
    templateUrl: 'app/view/imageList.html'
  }).when('/gallery/:galleryId/images/add', {
    controller: 'ImageAddController',
    templateUrl: 'app/view/imageAdd.html'
  });
});

GalleryAddController = function($scope, $resource, $location, GalleryResource) {
  $scope.gallery = {};
  return $scope.formSubmit = function() {
    return GalleryResource.save($scope.gallery, function(gallery, resHeaders) {
      return $location.path('/');
    });
  };
};

GalleryEditController = function($scope, $resource, $routeParams, $location, GalleryResource) {
  angular.extend(this, new GalleryAddController($scope, $resource, $location, GalleryResource));
  return $scope.gallery = GalleryResource.get({
    _id: $routeParams._id
  });
};

GalleryListController = function($scope, $resource, $window, $location, GalleryResource) {
  $scope.galleries = GalleryResource.query({});
  $scope.showButtons = function(loopScope) {
    return loopScope.buttonsVisible = true;
  };
  $scope.hideButtons = function(loopScope) {
    return loopScope.buttonsVisible = false;
  };
  return $scope.deleteGallery = function(gallery) {
    return gallery.$remove(function(gallery, responseHeaders) {
      return gallery.isDeleted = true;
    });
  };
};

ImageAddController = function($scope, $resource, $location, $routeParams, GalleryResource) {
  $scope.gallery = GalleryResource.get({
    _id: $routeParams.galleryId
  });
  $scope.image = {};
  $scope.formSubmit = function() {
    return GalleryResource.save($scope.gallery, function(gallery, resHeaders) {
      return $location.path('/');
    });
  };
  return $scope.uploadComplete = function(contents, completed) {
    console.log(contents);
    return console.log(completed);
  };
};

ImageListController = function($scope, $resource, $window, $location, $routeParams, ImageResource, GalleryResource) {
  $scope.galleryId = $routeParams.galleryId;
  $scope.gallery = GalleryResource.get({
    _id: $routeParams.galleryId
  });
  $scope.showButtons = function(loopScope) {
    return loopScope.buttonsVisible = true;
  };
  $scope.hideButtons = function(loopScope) {
    return loopScope.buttonsVisible = false;
  };
  return $scope.deleteImage = function(image) {
    return image.$remove(function(image, responseHeaders) {
      return image.isDeleted = true;
    });
  };
};

SweetGalleryApp.factory('GalleryResource', function($resource) {
  return $resource('/api/galleries/:_id', {
    _id: '@_id'
  });
});

SweetGalleryApp.factory('ImageResource', function($resource) {
  return $resource('/api/images/:_id', {
    _id: '@_id'
  });
});
